### ISSUE TITLE
"enableADAGUC" section in static/diagnosticsdata/... yml files break the portal pages

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-frontend#222]
When running locally the part: " enableADAGUC:..." in the yml files breaks some pf the pages. I commented it in the portal diagnostocsdata pages that I found to be broken:
 
e.g., 
```
enableADAGUC:
  - data_url: {STATICWMS}?source=c3smagic%2Frecipes%2Frecipe_miles_regimes_20190308_064506%2Fwork%2Fmiles_diagnostics%2Fmiles_regimes%2FEC-EARTH%2Fhistorical%2Fr2i1p1%2F1980-1989%2FDJF%2FRegimes%2FRegimesPattern_EC-EARTH_historical_r2i1p1_1980-1989_DJF.nc&&service=WMS&request=GetCapabilities
  - projectionbutton: true
  - layerselector: true
  - timeselector: false
  - styleselector: true
  - layers: []
```
